apiVersion: v1
kind: Service
metadata:
  name: opscenter-ext-lb
  labels:
    app: opscenter
spec:
  type: LoadBalancer
  ports:
  - port: 8888
    name: opsc-gui-port
  selector:
    app: opscenter

